### ISSUE TITLE
How can I get the camera dataset?

### ISSUE THREAD

**Issue by zzwu29** [JonasBchrt/raw-gnss-fusion#1]
Hi, @JonasBchrt, thank you for your great dataset! Would you consider publishing your camera data and calibration file? 
Thank you very much!

**Comment by JonasBchrt** [comment]
Hi @zzwu29 and thanks for your interest.

Unfortunately, I don't think I can help you with camera data. We were only interested in lidar, IMU, and GNSS when we recorded this dataset. And while our setup theoretically had cameras, I believe my university would have required me to initiate some ethics/privacy approval process first before I record and publish camera data with humans being visible in the captures, which I did not do.

With calibration file, do you mean the camera/vision calibration file?

**Comment by JonasBchrt** [comment]
This 3rd party dataset contains raw GNSS data and camera data, for example: https://github.com/HKUST-Aerial-Robotics/GVINS-Dataset

**Comment by zzwu29** [comment]
Thanks!
