### ISSUE TITLE
About timestamp of LiDAR point

### ISSUE THREAD

**Issue by Joanna-HE** [JonasBchrt/raw-gnss-fusion#2]
Hi,

Thank you for open sourcing three robot datasets with GNSS, IMU, and lidar data. I would like to use these datasets to test our algorithm, and would like to ask if there is a timestamp for each LiDAR point, if yes, what is the value type of the point's time? Hope to hear from you.

Best regards,

Dongjiao HE

**Comment by JonasBchrt** [comment]
Hi and thanks for your interest.
I am not sure if I understand your question correctly, but maybe this answer helps:
* The topic with the lidar data is `/hesai/pandar`, which is of type `sensor_msgs/PointCloud2`. You can find the message definition [here](http://docs.ros.org/en/melodic/api/sensor_msgs/html/msg/PointCloud2.html).
* Each point cloud has a timestamp in the header, i.e., in `/hesai/pandar/header`. The header is defined [here](http://docs.ros.org/en/melodic/api/std_msgs/html/msg/Header.html).
* The structure of the point cloud data is defined in the topic `hesai/pandar/fields`, which is an array of type `PointField`, which is defined [here](http://docs.ros.org/en/melodic/api/sensor_msgs/html/msg/PointField.html).
* If you subscribe to the topic and look at one of the bags, then you can see that the structure includes an element called `"timestamp"` with an offset of 24 bytes and of type `FLOAT64`.
* The actual point data is then in `/hesai/pandar/data` and stored according to the definition in `/hesai/pandar/fields`, including the timestamps.

**Comment by Joanna-HE** [comment]
Thanks for your kind and prompt reply, my problem is solved perfectly.
