### ISSUE TITLE
Question about the ionosphere parameters of your dataset

### ISSUE THREAD

**Issue by Joanna-HE** [JonasBchrt/raw-gnss-fusion#3]
Hi,

Thanks a lot for open sourcing the datasets with LiDAR, IMU and GNSS. I would like to ask if there are ionosphere parameters for those datasets, which could be used to evaluate the ionosphere and troposphere delays.

Best regards,

**Comment by JonasBchrt** [comment]
Hi,

When I use ionosphere parameters, then I usually just use those that I can download for free from [the NASA file server](https://cddis.nasa.gov/archive/gnss/) or [the BKG file server](https://igs.bkg.bund.de/). They have IONEX files (in the `products` directory) as well as RINEX files with some ionosphere parameters in the header. An example for the latter can be found in the `navigation_data` directory in this repository.

Not sure if this is what you're looking for...

**Comment by Joanna-HE** [comment]
Thanks for your prompt reply. My problem is solved.

Best regards,

Joanna
________________________________
寄件者: Jonas Beuchert ***@***.***>
寄件日期: 2023年1月7日 下午 05:38
收件者: JonasBchrt/raw-gnss-fusion ***@***.***>
副本: He Dongjiao ***@***.***>; Author ***@***.***>
主旨: Re: [JonasBchrt/raw-gnss-fusion] Question about the ionosphere parameters of your dataset (Issue #3)


Hi,

When I use ionosphere parameters, then I usually just use those that I can download from the NASA file server<https://cddis.nasa.gov/archive/gnss/> or the BKG file server<https://igs.bkg.bund.de/>. They have IONEX files (in the products directory) as well as RINEX files with some ionosphere parameters in the header. An example for the latter can be found in the navigation_data directory in this repository.

Not sure if this is what you're looking for...
