### ISSUE TITLE
Question about the timestamps synchronization of the IMU data and LiDAR points

### ISSUE THREAD

**Issue by lawrence-cn** [JonasBchrt/raw-gnss-fusion#4]
Hello,
Thank you very much for your opensource. The IMU data and LiDAR points come from different devices (HESAI XT32 and Bosch BMI0856), so how did you achieve the synchronization of their timestamps? Is there any synchronization pulse signal generated from external hardwares? Hope for your answer~

**Comment by JonasBchrt** [comment]
Brief answer: both devices support hardware time stamping and we synchronise clocks using PTP running on a Ubuntu machine to which both devices are connected via ethernet.

**Comment by lawrence-cn** [comment]
Thank you for your helpful answer!
