### ISSUE TITLE
Questions about a technique approch stated in the paper

### ISSUE THREAD

**Issue by cicizou** [JonasBchrt/raw-gnss-fusion#5]
Hi, thanks a lot for sharing such good work with the community! I have some questions about the article and looking forward to having a discussion with you.

I have noticed that you claimed "We estimate the transformation T_EW jointly with the platform position in frame W such that T_EW absorbs any large changes/discontinuities due to GNSS convergence while the position estimate in W remains unaffected." in the paper. However, in my opinion, it is hard to balance between the T_EW and platform positions and to make large changes only affect the T_EW but not the platform positions, especially when the GNSS signal has many outliers. I am curious about how you make it and I would appreciate it if you could please explain this point more deeply and in more detail.

Hope to hear from you!

**Comment by JonasBchrt** [comment]
Hi, just some thoughts out of the top of my mind:
* I think the most important point is to have adequate uncertainties associated with (1) the robot state, (2) the measurements/observations, and (3) T_EW. It sounds like in your situation, the uncertainty of T_EW should maybe be higher and/or decrease slower. You might need to be a bit more conservative and accept slower convergence of T_EW if sky visibility is bad and/or measurements are noisy at the beginning. But that's just guessing.
* I agree that outliers can be a problem. You need (and probably already have) some strategy to identify and remove or down-weight them and/or want to use a robust cost function for good performance. Which indicators you can use to do that partially depends on the data reported by your receiver I think. You can look at signal strengths, measurement uncertainties, the duration for which you've seen a signal already, how stable a signal is, satellite elevation, compare different measurements, maybe check estimates for plausibility... I think I'd like to refer you to existing literature for that or maybe the manual of your receiver.
* If you really have problems, you could also introduce a dedicated initialisation phase where you only use GNSS observations to adjust T_EW, but not the local position, until you're certain that your T_EW estimate is good, e.g., it's uncertainty is below a certain threshold. It's only a small change to the algorithm. (Didn't use it for the results presented in the arXiv paper, though.)
* In general, I must admit that I only used one type of GNSS receiver (the C099 from ublox) for the presented experiments and it's definitely possible that other receivers make your life harder. The quality of the setup (including antenna) really matters for GNSS processing, I think. (Although, the receiver and antenna that I used are really not top-notch, I think.) Especially with the setup on the quadruped, it took me a while to come up with a configuration where electromagnetic inference was low enough to have a good number of good satellite signals. I also sometimes use factor-graph optimisation for pseudoranges measured with my own self-made low-cost GNSS receiver (https://github.com/SnapperGPS) and outliers are really a bit more annoying there than they are with the ublox 😭

**Comment by cicizou** [comment]
Thanks a lot for your comprehensive and detailed response! Actually, we are trying to do research on the tightly fusing of LiDAR and GNSS measurements, but it is found to have so many difficulties. Thanks so much for your open-source work which could be great guidance for us.
